version: '{build}'
branches:
  only:
  - master
skip_branch_with_pr: true
image: Visual Studio 2022
configuration: Release
platform: Any CPU
clone_script:
- cmd: >-
    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    
    cd %APPVEYOR_BUILD_FOLDER%
    
    git checkout -qf %APPVEYOR_REPO_COMMIT%
    
    git submodule update --init --recursive
cache:
- packages -> **\packages.config
- '%USERPROFILE%\.nuget\packages -> **\project.json'
before_build:
- ps: >-
    $env:GIT_TAG = git describe --always --tags --exclude latest
    
    nuget restore -verbosity detailed
build:
  verbosity: minimal
after_build:
- ps: >-
    Get-Content GitVersion.cs

    Move-Item Build\QuickLook-$env:GIT_TAG.msi QuickLook-$env:GIT_TAG.msi
    
    Move-Item Build\QuickLook-$env:GIT_TAG.zip QuickLook-$env:GIT_TAG.zip

artifacts:
- path: QuickLook-%GIT_TAG%.zip
  name: QuickLook-%GIT_TAG%
- path: QuickLook-%GIT_TAG%.msi
  name: QuickLook-%GIT_TAG%
# deploy:
# - provider: GitHub
#   auth_token:
#     secure: 5CSvkfKBq9kUho529L1tkH5ywQQFJY/A8Y6lNoHGJFi7mnSqQAaoiVPbUVU4a/KC
#   artifact: QuickLook-$(APPVEYOR_REPO_TAG_NAME)
#   draft: true
#   on:
#     APPVEYOR_REPO_TAG: true
